<!--  -->
<!--    JavaScripts-->
<!--    =============================================-->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.7/js/tether.min.js"></script>
<script src="{{asset('website/assets/lib/bootstrap/dist/js/bootstrap.min.js')}}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.isotope/3.0.6/isotope.pkgd.min.js"></script>
<script src="{{asset('website/assets/js/core.js')}}"></script>
<script src="{{asset('website/assets/js/main.js')}}"></script>
